import PhotoEnhancerTool from "@/components/tools/image/PhotoEnhancerTool";
import ToolLayout from "@/components/tools/shared/ToolLayout";

export const metadata = {
	title: "Free Photo Enhancer Online - No Signup | 30tools",
	description:
		"Enhance photo quality with AI-powered image enhancement 100% free, no signup required, and privacy-focused processing in your browser.",
	keywords:
		"photo enhancer, free online tool, no signup, image, photo enhancer online, 30tools",
	alternates: {
		canonical: "https://30tools.com/photo-enhancer",
	},
	openGraph: {
		title: "Free Photo Enhancer Online - No Signup | 30tools",
		description:
			"Enhance photo quality with AI-powered image enhancement 100% free, no signup required, and privacy-focused processing in your browser.",
		url: "https://30tools.com/photo-enhancer",
		siteName: "30tools",
		images: [{ url: "/api/og?title=Free%20Photo%20Enhancer%20Online%20-%20No%20Signup" }],
		type: "website",
	},
	twitter: {
		card: "summary_large_image",
		title: "Free Photo Enhancer Online - No Signup | 30tools",
		description:
			"Enhance photo quality with AI-powered image enhancement 100% free, no signup required, and privacy-focused processing in your browser.",
		images: ["/api/og?title=Free%20Photo%20Enhancer%20Online%20-%20No%20Signup"],
	},
	robots: { index: true, follow: true },
};

export default async function ToolPage() {
	const tool = {
		id: "photo-enhancer",
		name: "Photo Enhancer",
		description: "Enhance photo quality with AI-powered image enhancement",
		route: "/photo-enhancer",
		extraSlugs: [
			"ai-photo-enhancer",
			"cut-photo",
			"free-photo-grid-maker",
			"ig-photo-download-hd",
			"instagram-profile-photo-hd",
			"online-photo-editor",
			"photo-collage-maker",
			"photo-filter-editor",
			"photo-quality-improver",
			"upscale-illustration-online-free",
		],
		popular: true,
		category: "image",
		features: [
			"AI-Powered Upscaling: Increase image resolution without losing clarity or introducing artifacts.",
			"Noise Reduction: Automatically remove grain and digital noise from low-light photos.",
			"Color Correction: Enhance contrast, saturation, and vibrancy with a single click.",
			"Browser-Based Processing: Fast, secure, and entirely private image enhancement without cloud uploads.",
		],
		howTo: {
			name: "How to Enhance a Photo Online",
			steps: [
				{
					name: "Upload Photo",
					text: "Select a blurry, low-resolution, or noisy photo from your device.",
				},
				{
					name: "Apply AI Enhancement",
					text: "Click the 'Enhance' button. Our AI will analyze the image and apply smart corrections to improve clarity and color.",
				},
				{
					name: "Compare & Download",
					text: "Use the before/after slider to see the improvements, then download your high-quality enhanced image.",
				},
			],
		},
		faqs: [
			{
				question: "How does the AI photo enhancer work?",
				answer: "The tool uses machine learning algorithms running directly in your browser to analyze patterns in your image. It then predicts and fills in missing details, removes noise, and adjusts colors to create a sharper, clearer result.",
			},
			{
				question: "Can I enhance old, blurry photos?",
				answer: "Yes, the AI is specifically trained to improve the sharpness of out-of-focus or compressed images, making it great for restoring older digital photos.",
			},
			{
				question: "Are my enhanced photos kept private?",
				answer: "Absolutely. Unlike other services, our enhancer processes the image locally on your device. No data is sent to our servers, guaranteeing complete privacy.",
			},
		],
	};
	const breadcrumbs = [
		{
			name: "Image Tools",
			url: "/image-tools",
		},
		{
			name: "Photo Enhancer",
			url: "/photo-enhancer",
		},
	];
	const relatedTools = [
		{
			id: "background-remover",
			name: "Background Remover",
			description: "Remove image backgrounds automatically with AI",
			route: "/background-remover",
			extraSlugs: [
				"remove-background-from-signature-free",
				"transparent-background-maker",
				"picture-background-eraser",
				"duplicate-line-remover",
				"background-gradient-tool",
				"background-gradient-creator",
			],
			popular: true,
			category: "image",
		},
		{
			id: "base64-to-image-converter",
			name: "Base64 to Image Converter",
			description:
				"Free base64 to image converter tool to process your data instantly with privacy-friendly browser-based workflows.",
			route: "/base64-to-image-converter",
			extraSlugs: [
				"add-text-to-image",
				"all-in-one-unit-converter",
				"audio-converter",
				"audio-converter-mp3",
				"avi-file-to-mp4-online",
				"avi-to-mp4-converter",
				"avi-video-converter",
				"base64-encoder-decoder",
				"base64-image",
				"base64-to-image",
				"base64-to-image-converter-tool",
				"base64-to-text",
				"base64-tool",
				"change-audio-format",
				"change-avi-to-mp4",
				"change-flv-to-mp4",
				"change-image-dimensions",
				"change-m4a-to-mp3",
				"change-mkv-to-mp4",
				"change-mov-to-mp4",
				"change-ogg-to-mp3",
				"change-pdf-orientation",
				"change-video-type",
				"change-wav-to-mp3",
				"change-webm-to-mp4",
				"click-to-chat-whatsapp",
				"compress-files-to-zip",
				"compress-ogg-to-mp3",
				"compress-wav-to-mp3",
				"convert-audio-format",
				"convert-image-to-jpg",
				"convert-picture-to-string",
				"convert-video-format",
				"date-to-epoch",
				"decode-base64-image",
				"document-converter",
				"docx-to-pdf-converter",
				"ebook-format-converter",
				"encode-image-base64",
				"epoch-converter",
				"epoch-to-datetime",
				"epub-converter",
				"file-converter",
				"fit-photo-to-instagram-story",
				"flv-file-to-mp4-online",
				"flv-to-mp4-converter",
				"flv-video-converter",
				"folder-to-zip-converter",
				"format-html-css-js",
				"format-sql-online",
				"free-base64-to-image-converter-online",
				"image-format-changer",
				"image-to-base64",
				"image-to-pdf-converter",
				"insta-story-size-converter",
				"instagram-reels-to-mp4",
				"m4a-audio-converter",
				"m4a-file-to-mp3-online",
				"m4a-to-mp3-converter",
				"m4a-to-mp3-online",
				"md-html-converter",
				"md-to-txt-converter",
				"measurement-converter",
				"metric-imperial-converter",
				"mkv-file-to-mp4-online",
				"mkv-to-mp4-converter",
				"mkv-video-converter",
				"mov-file-to-mp4-online",
				"mov-to-mp4",
				"mov-to-mp4-converter",
				"mov-video-converter",
				"movie-to-mp3-converter",
				"mp3-converter",
				"mp3-converter-online",
				"mp4-audio-converter",
				"mp4-converter-online",
				"mp4-to-mp3",
				"ogg-audio-converter",
				"ogg-file-to-mp3-online",
				"ogg-to-mp3-converter",
				"pdf-to-docx-converter",
				"pdf-to-epub-converter",
				"photos-to-pdf-converter",
				"pptx-to-pdf-converter",
				"quicktime-to-mp4",
				"readme-to-html",
				"save-snaps-to-gallery",
				"text-fo-base64",
				"tiktok-aspect-ratio-converter",
				"tiktok-mp3-converter",
				"tiktok-music-converter",
				"tiktok-to-mp3-online",
				"timestamp-converter",
				"timezone-converter",
				"unit-converter",
				"unix-timestamp-to-date",
				"uppercase-to-lowercase",
				"url-string-converter",
				"url-to-pdf-converter",
				"usd-to-eur-converter",
				"video-converter",
				"video-to-mp3-converter",
				"wav-audio-converter",
				"wav-file-to-mp3-online",
				"wav-to-mp3-converter",
				"webm-file-to-mp4-online",
				"webm-to-mp4-converter",
				"webm-video-converter",
				"world-clock-converter",
				"xlsx-to-pdf-converter",
				"youtube-to-mp3-high-quality",
				"youtube-to-mp4-converter",
			],
			popular: false,
			category: "image",
		},
		{
			id: "convert-to-ico",
			name: "Convert to ICO",
			description:
				"Free convert to ico tool to process your data instantly with privacy-friendly browser-based workflows.",
			route: "/convert-to-ico",
			extraSlugs: [
				"convert-audio-format",
				"convert-avi-to-mp4",
				"convert-doc-to-pdf",
				"convert-epoch-time",
				"convert-flv-to-mp4",
				"convert-html-to-pdf",
				"convert-landscape-to-portrait-video",
				"convert-m4a-to-mp3",
				"convert-md-to-html",
				"convert-mkv-to-mp4",
				"convert-money-online",
				"convert-mov-to-mp4",
				"convert-mp4-to-gif",
				"convert-mp4-to-mp3",
				"convert-mp4-video-to-mp3",
				"convert-ogg-to-mp3",
				"convert-pdf-to-doc",
				"convert-picture-to-string",
				"convert-png-to-favicon",
				"convert-ppt-to-pdf",
				"convert-string-to-binary",
				"convert-text-case",
				"convert-text-to-audio",
				"convert-tiktok-to-mp3",
				"convert-time-across-zones",
				"convert-time-to-timestamp",
				"convert-to-epub-online",
				"convert-to-ico-tool",
				"convert-units-online",
				"convert-video-file-to-mp3",
				"convert-video-format",
				"convert-wav-to-mp3",
				"convert-webm-to-mp4",
				"convert-xls-to-pdf",
				"free-convert-to-ico-online",
			],
			popular: false,
			category: "image",
		},
	];

	return (
		<>
			<script
				type="application/ld+json"
				dangerouslySetInnerHTML={{
					__html: JSON.stringify({
						"@context": "https://schema.org",
						"@type": "SoftwareApplication",
						name: "Photo Enhancer",
						description:
							"Enhance photo quality with AI-powered image enhancement",
						url: "https://30tools.com/photo-enhancer",
						applicationCategory: "UtilitiesApplication",
						operatingSystem: "Any",
						offers: { "@type": "Offer", price: "0", priceCurrency: "USD" },
					}),
				}}
			/>

			<ToolLayout
				tool={tool}
				breadcrumbs={breadcrumbs}
				relatedTools={relatedTools}
			>
				<PhotoEnhancerTool />
			</ToolLayout>
		</>
	);
}
