// Comprehensive FAQ database for Generator Tools
export const GENERATOR_TOOLS_FAQS = {
  // General Generator Tools FAQs
  general: [
    {
      question: "Are these generator tools really free to use?",
      answer:
        "Yes! All our generator tools are completely free with no hidden charges, registration requirements, or usage limits. Create unlimited content without any restrictions.",
    },
    {
      question: "Do I need to sign up to use the generators?",
      answer:
        "No signup required! All generator tools work instantly in your browser. Simply visit the tool page and start creating content immediately.",
    },
    {
      question: "Can I use generated content for commercial purposes?",
      answer:
        "Yes! All content generated by our tools can be used for personal and commercial purposes. There are no licensing restrictions on the output you create.",
    },
    {
      question: "How do the AI generators work?",
      answer:
        "Our AI generators use advanced machine learning models to create content based on your inputs. All processing happens quickly and delivers high-quality, creative results.",
    },
    {
      question: "Are the generators mobile-friendly?",
      answer:
        "Absolutely! All our generators are fully responsive and work perfectly on smartphones, tablets, and desktop computers for content creation on the go.",
    },
    {
      question: "Can I share generated content on social media?",
      answer:
        "Yes! Our generators are designed for social media sharing. Many tools include built-in sharing features and export options optimized for different platforms.",
    },
  ],

  // Aesthetic Bio Generator specific FAQs
  "aesthetic-bio-generator": [
    {
      question: "What makes a bio aesthetic?",
      answer:
        "Aesthetic bios use special fonts, emojis, symbols, and creative formatting to create visually appealing profiles. They often include themes like soft girl, dark academia, vintage, or minimalist styles.",
    },
    {
      question: "Which platforms work with generated bios?",
      answer:
        "Our bios work perfectly on Instagram, Twitter, TikTok, Discord, and most social media platforms. Each bio is optimized for character limits and platform-specific features.",
    },
    {
      question: "How many aesthetic themes are available?",
      answer:
        "We offer 6 carefully curated aesthetic themes: Soft Girl, Dark Academia, Vintage, Minimalist, Y2K, and Cottagecore. Each theme has unique fonts, emojis, and styling.",
    },
    {
      question: "Can I customize the generated bios?",
      answer:
        "Yes! Use the generated bio as a starting point and customize it with your own text, emojis, and personal touches. The tool provides a creative foundation you can build upon.",
    },
    {
      question: "Are the fonts in bios compatible with all devices?",
      answer:
        "Our aesthetic fonts use Unicode characters that display correctly on most modern devices and platforms. Some older devices might show fallback fonts.",
    },
    {
      question: "How often are new aesthetic styles added?",
      answer:
        "We regularly update our aesthetic themes based on trending styles and user feedback. Follow us for updates on new themes and features.",
    },
    {
      question: "Can I generate multiple bios at once?",
      answer:
        "Yes! Generate multiple variations and save your favorites. Try different themes and combinations to find the perfect aesthetic for your profile.",
    },
    {
      question: "Do the bios help with follower growth?",
      answer:
        "Aesthetic bios can help attract followers by making your profile more visually appealing and memorable. A good bio is crucial for first impressions on social media.",
    },
  ],

  // Startup Name Generator specific FAQs
  "startup-name-generator": [
    {
      question: "How does the AI generate startup names?",
      answer:
        "Our AI analyzes thousands of successful startup names, industry trends, and brandable patterns to generate creative, memorable names that sound professional and modern.",
    },
    {
      question: "Are domain names available for generated names?",
      answer:
        "We provide domain availability hints for popular extensions (.com, .io, .co). However, we recommend checking current availability as domains are constantly being registered.",
    },
    {
      question: "What industries does the generator focus on?",
      answer:
        "Our generator specializes in tech, SaaS, fintech, AI, and modern digital companies. It understands current naming trends in the startup ecosystem.",
    },
    {
      question: "Can I trademark generated startup names?",
      answer:
        "Generated names are suggestions only. Always conduct proper trademark searches and legal verification before using any name for your business or brand.",
    },
    {
      question: "How do I choose the best name for my startup?",
      answer:
        "Look for names that are memorable, easy to pronounce, brandable, and relevant to your industry. Consider domain availability and avoid names that are too similar to existing companies.",
    },
    {
      question: "Does the generator consider naming trends?",
      answer:
        "Yes! Our AI incorporates current startup naming trends, including short names, made-up words, compound words, and tech-friendly patterns popular with VCs and founders.",
    },
    {
      question: "Can I generate names for specific business types?",
      answer:
        "Absolutely! The generator can focus on different business types like SaaS, marketplace, AI tools, fintech, and more. Specify your industry for better results.",
    },
    {
      question: "How many name suggestions can I generate?",
      answer:
        "Generate unlimited name suggestions! Keep generating until you find the perfect name for your startup. Save your favorites and share them with your team.",
    },
  ],

  // Fake Chat Generator specific FAQs
  "fake-chat-generator": [
    {
      question: "What chat platforms can I simulate?",
      answer:
        "Currently supports WhatsApp, Instagram DM, iMessage, and Discord. Each platform has authentic design elements including colors, fonts, and interface layouts.",
    },
    {
      question: "How realistic do the fake chats look?",
      answer:
        "Our fake chats are highly realistic with accurate platform designs, proper timestamp formatting, and authentic visual elements that closely match real conversations.",
    },
    {
      question: "Can I export chats as images?",
      answer:
        "Yes! Export your fake chats as high-quality PNG or JPG images perfect for social media, memes, presentations, or any other use case you have in mind.",
    },
    {
      question: "What are fake chats commonly used for?",
      answer:
        "Popular uses include creating memes, social media content, comedy skits, educational examples, marketing materials, and creative storytelling projects.",
    },
    {
      question: "Can I create group conversations?",
      answer:
        "Currently, our generator focuses on two-person conversations for maximum realism and simplicity. Group chat features may be added in future updates.",
    },
    {
      question: "Are there character limits for messages?",
      answer:
        "Each platform has realistic character limits that match the actual apps. Long messages will wrap naturally, just like in real conversations.",
    },
    {
      question: "Can I customize profile pictures and names?",
      answer:
        "Yes! Customize contact names and use generic profile pictures to create more personalized and realistic-looking conversations.",
    },
    {
      question: "Is this tool safe for creating content?",
      answer:
        "Yes, but use responsibly! These tools are for entertainment, education, and creative purposes. Don't use fake chats to deceive, harass, or mislead others.",
    },
  ],

  // AI Image Generator specific FAQs
  "ai-image-generator": [
    {
      question: "How does text-to-image AI work?",
      answer:
        "Our AI model converts your text descriptions into images by understanding the relationships between words and visual concepts, then generating corresponding artwork.",
    },
    {
      question: "What types of images can I generate?",
      answer:
        "Generate artwork, illustrations, concepts, designs, photography styles, abstract art, characters, landscapes, objects, and much more from simple text descriptions.",
    },
    {
      question: "How long does image generation take?",
      answer:
        "Most images generate within 10-30 seconds depending on complexity. Simple prompts are faster, while detailed descriptions may take slightly longer.",
    },
    {
      question: "What resolution are the generated images?",
      answer:
        "Generated images are high-quality and suitable for most digital uses including social media, blogs, presentations, and creative projects.",
    },
    {
      question: "Can I use generated images commercially?",
      answer:
        "Yes! All generated images can be used for personal and commercial purposes. You own the rights to images you create with our generator.",
    },
    {
      question: "How do I write better prompts?",
      answer:
        "Be descriptive and specific! Include details about style, colors, composition, mood, and setting. For example: 'A peaceful sunset over mountains, oil painting style, warm colors'.",
    },
    {
      question: "Can I generate images in different art styles?",
      answer:
        "Absolutely! Specify art styles in your prompts like 'watercolor', 'digital art', 'photography', 'cartoon', 'realistic', or any other style you prefer.",
    },
    {
      question: "Is there a limit to how many images I can generate?",
      answer:
        "No limits! Generate as many images as you need for your projects. Our service is completely free with unlimited generations.",
    },
  ],

  // AI Voice Generator specific FAQs
  "ai-voice-generator": [
    {
      question: "What voice options are available?",
      answer:
        "We offer multiple AI voices including male and female options with different accents, tones, and speaking styles to suit various content needs.",
    },
    {
      question: "Can I download the generated audio?",
      answer:
        "Yes! Download your generated speech as high-quality MP3 files that you can use in videos, podcasts, presentations, or any other audio project.",
    },
    {
      question: "What languages does the voice generator support?",
      answer:
        "Currently focused on English with multiple accent variations. Additional languages may be added based on user demand and feedback.",
    },
    {
      question: "How natural do the AI voices sound?",
      answer:
        "Our AI voices use advanced text-to-speech technology to create natural-sounding speech with proper pronunciation, intonation, and pacing.",
    },
    {
      question: "Is there a character limit for text input?",
      answer:
        "You can generate speech for substantial amounts of text. Very long texts may be processed in segments for optimal quality and performance.",
    },
    {
      question: "Can I use generated voices commercially?",
      answer:
        "Yes! Use generated voices in your commercial projects, videos, podcasts, presentations, and other content without licensing restrictions.",
    },
    {
      question: "How do I get the best results?",
      answer:
        "Use clear, well-punctuated text. Add commas for natural pauses and format text as you would want it spoken aloud for the most natural results.",
    },
    {
      question: "Can I adjust speech speed or tone?",
      answer:
        "Currently, voices use optimized natural speech patterns. Advanced controls for speed, tone, and emphasis may be added in future updates.",
    },
  ],

  // Excuse Generator specific FAQs
  "excuse-generator": [
    {
      question: "What kind of excuses can I generate?",
      answer:
        "You can generate excuses for various categories including Work, School, Social Events, Family Gatherings, and more. Each category has specific scenarios tailored to it.",
    },
    {
      question: "Are the excuses believable?",
      answer:
        "We offer different believability levels ranging from 'Highly Plausible' to 'Ridiculous'. Choose the level that fits your situation and how much risk you want to take!",
    },
    {
      question: "Can I use these excuses for real situations?",
      answer:
        "While our excuses are designed to sound realistic (or funny), we recommend using them responsibly. We are not responsible for any consequences of using these excuses!",
    },
    {
      question: "How does the AI create excuses?",
      answer:
        "Our AI analyzes common social situations and successful excuse patterns to generate responses that sound natural and convincing for the selected context.",
    },
    {
      question: "Can I edit the generated excuses?",
      answer:
        "Absolutely! Use the generated excuse as a base and tweak the details to fit your specific situation perfectly. Adding personal details makes them more convincing.",
    },
    {
      question: "Is there a limit to how many excuses I can make?",
      answer:
        "No limits! Generate as many excuses as you need until you find the perfect one. It's completely free and unlimited.",
    },
    {
      question: "Do you save the excuses I generate?",
      answer:
        "No, we don't store any of your generated excuses or personal data. All generation happens in your browser for privacy.",
    },
    {
      question: "Can I share excuses directly?",
      answer:
        "Yes, you can easily copy the excuse to your clipboard or share it directly to messaging apps if you're on a mobile device.",
    },
  ],

  // AI Poetry Generator specific FAQs
  "ai-poetry-generator": [
    {
      question: "How does the AI write poems?",
      answer:
        "Our AI has been trained on thousands of classic and modern poems to understand rhyme schemes, meter, and poetic structures. It uses this knowledge to create original poetry based on your inputs.",
    },
    {
      question: "What types of poems can I generate?",
      answer:
        "You can generate various poetic forms including Haiku, Sonnet, Free Verse, Limerick, Acrostic, and Rhyming Couplets. Simply select your preferred style before generating.",
    },
    {
      question: "Are the generated poems unique?",
      answer:
        "Yes! Every poem is generated from scratch based on your specific topic and mood. You won't get the same poem twice, ensuring your content is original.",
    },
    {
      question: "Can I use these poems for special occasions?",
      answer:
        "Absolutely! Our generator is perfect for writing poems for birthdays, anniversaries, weddings, Valentine's Day, or just to express your feelings to someone special.",
    },
    {
      question: "Do I own the copyright to the poems?",
      answer:
        "Yes, you own the rights to any poem you generate with our tool. You can publish them, use them in greeting cards, or share them on social media without restrictions.",
    },
    {
      question: "Can I specify the mood of the poem?",
      answer:
        "Yes, you can choose from various moods like Romantic, Sad, Funny, Inspirational, or Mysterious to ensure the tone matches your intent perfectly.",
    },
    {
      question: "Is there a limit to poem length?",
      answer:
        "You can choose between Short, Medium, and Long options. The AI will adjust the stanza count and complexity based on your selection.",
    },
    {
      question: "Can I edit the poems after generation?",
      answer:
        "Of course! We encourage you to use the generated poem as a draft and tweak lines or words to add your personal touch and make it perfect.",
    },
  ],
};

// Helper function to get FAQs for a specific generator tool
export const getGeneratorToolFAQs = (toolId) => {
  const toolFAQs = GENERATOR_TOOLS_FAQS[toolId] || [];
  const generalFAQs = GENERATOR_TOOLS_FAQS.general || [];

  return [...toolFAQs, ...generalFAQs];
};

// Helper function to search generator FAQs
export const searchGeneratorFAQs = (query) => {
  const allFAQs = [];

  // Collect all FAQs
  Object.values(GENERATOR_TOOLS_FAQS).forEach((faqs) => {
    if (Array.isArray(faqs)) {
      allFAQs.push(...faqs);
    }
  });

  // Search in questions and answers
  return allFAQs.filter(
    (faq) =>
      faq.question.toLowerCase().includes(query.toLowerCase()) ||
      faq.answer.toLowerCase().includes(query.toLowerCase()),
  );
};

export default GENERATOR_TOOLS_FAQS;
