import ToolLayout from "@/components/tools/shared/ToolLayout";
import MetaTagGenerator from "@/components/tools/built-ins/MetaTagGenerator";


export const metadata = {
	title: "Free Meta Tag Generator Online – Fast & No Signup | 30tools",
	description: "Free meta tag generator tool to process your data instantly with privacy-friendly browser-based workflows. 100% free, fast, and no signup required.",
	keywords: "meta tag generator, free online tool, no signup",
	alternates: {
		canonical: "https://30tools.com/meta-tag-generator",
	},
	openGraph: {
		title: "Free Meta Tag Generator Online – Fast & No Signup | 30tools",
		description: "Free meta tag generator tool to process your data instantly with privacy-friendly browser-based workflows. 100% free, fast, and no signup required.",
		url: "https://30tools.com/meta-tag-generator",
		siteName: "30tools",
		images: [{ url: "/og-image.jpg" }],
		type: "website",
	},
	twitter: {
		card: "summary_large_image",
		title: "Free Meta Tag Generator Online – Fast & No Signup | 30tools",
		description: "Free meta tag generator tool to process your data instantly with privacy-friendly browser-based workflows. 100% free, fast, and no signup required.",
		images: ["/og-image.jpg"],
	},
	robots: { index: true, follow: true },
};

export default async function ToolPage() {
	const tool = {
        "id": "meta-tag-generator",
        "name": "Meta Tag Generator",
        "description": "Free meta tag generator tool to process your data instantly with privacy-friendly browser-based workflows.",
        "route": "/meta-tag-generator",
        "extraSlugs": [
                "free-meta-tag-generator",
                "free-meta-tag-generator-online",
                "meta-header-generator",
                "meta-tag-generator-tool",
                "meta-tags-generator"
        ],
        "popular": false,
        "category": "seo",
		"features": [
			"Generate Essential HTML Meta Tags (Title, Description, Keywords)",
			"Create Open Graph Tags for Social Media Sharing",
			"Configure Robots Directives (Index/NoIndex, Follow/NoFollow)",
			"Real-Time Code Preview and Copy-to-Clipboard",
			"100% Free and Browser-Based — No Server Processing"
		],
		"article": `
## The Foundation of On-Page SEO
Meta tags are snippets of text that describe a page's content. They don't appear on the page itself, but only in the page's code. The Meta Tag Generator takes the guesswork out of crafting perfectly formatted HTML tags that search engines and social media platforms rely on.

### Optimize for Click-Through Rates (CTR)
While Google might not use the meta description directly for ranking, a compelling description is your elevator pitch on the search engine results page (SERP). A well-written meta description generated by our tool can significantly increase your CTR, bringing more traffic to your site.

### Comprehensive Tag Support
Beyond standard titles and descriptions, our generator handles the intricate tags required for modern web publishing. This includes Open Graph tags for Facebook, Twitter Cards for X, canonical URL definitions, and viewport settings for mobile responsiveness.
		`,
		"howTo": {
			"name": "How to Generate Meta Tags",
			"steps": [
				{
					"name": "Enter Page Details",
					"text": "Fill in the form with your page's title, description, and primary keywords."
				},
				{
					"name": "Configure Social Media",
					"text": "Add the URL of your featured image and the author's handle to generate Open Graph and Twitter Card tags."
				},
				{
					"name": "Set Indexing Rules",
					"text": "Choose whether you want search engines to index the page and follow its links."
				},
				{
					"name": "Copy the Code",
					"text": "Click the copy button and paste the generated HTML block directly into the <head> section of your website."
				}
			]
		},
		"faqs": [
			{
				"question": "Do meta keywords still matter for SEO?",
				"answer": "No. Google officially announced years ago that they do not use the meta keywords tag for ranking. However, some smaller or enterprise search engines might still reference it."
			},
			{
				"question": "How long should my meta description be?",
				"answer": "We recommend keeping meta descriptions between 140 and 160 characters. Any longer, and search engines will likely truncate the text with an ellipsis (...)."
			},
			{
				"question": "Is this tool safe to use for client websites?",
				"answer": "Absolutely. The generation happens entirely in your browser using JavaScript. No text you enter is sent to our servers."
			}
		]
};

	return (
		<>
			<script
				type="application/ld+json"
				dangerouslySetInnerHTML={{
					__html: JSON.stringify({
						"@context": "https://schema.org",
						"@type": "SoftwareApplication",
						name: tool.name,
						description: tool.description,
						url: "https://30tools.com/meta-tag-generator",
						applicationCategory: "UtilitiesApplication",
						operatingSystem: "Any",
						offers: { "@type": "Offer", price: "0", priceCurrency: "USD" },
					}),
				}}
			/>

			<ToolLayout tool={{ ...tool, category: "seo" }}>
				<MetaTagGenerator />
			</ToolLayout>
		</>
	);
}
